### ISSUE TITLE
[Feature request] Honour bin-dir in composer.json

### ISSUE THREAD

**Issue by madflow** [beeblebrox3/vscode-behat-checker#11]
+ If bin-dir or COMPOSER_BIN_DIR is present - use that
+ Else try vendor/bin

https://getcomposer.org/doc/articles/vendor-binaries.md#can-vendor-binaries-be-installed-somewhere-other-than-vendor-bin-

Thanks!

**Comment by beeblebrox3** [comment]
Thanks, @madflow . I didn't know this.

**Comment by beeblebrox3** [comment]
Done! Version 1.0.4 will detect this config and use it.
Thanks, @madflow .
