### ISSUE TITLE
Add configuration option for `behatChecker.behatExecutable` to configure executable location

### ISSUE THREAD

**Issue by aziz** [beeblebrox3/vscode-behat-checker#14]
Please add a configuration option `behatChecker.behatExecutable` to configure executable location. our old project is storing behat executable somewhere outside the vendor directory and I should be able to configure it.

**Comment by beeblebrox3** [comment]
Are you using composer and the [`bin` config](https://getcomposer.org/doc/articles/vendor-binaries.md)?

**Comment by aziz** [comment]
Yes, I have this is my `composer.json` file:
```
    "config": {
        "bin-dir": "bin/"
    }
```

**Comment by beeblebrox3** [comment]
On the newest version it should be working ([this issue](https://github.com/beeblebrox3/vscode-behat-checker/issues/11)).
The `composer.json` is on the root of your project?

**Comment by aziz** [comment]
> The composer.json is on the root of your project?

Yes.

I'm using the latest (1.0.4) and it's not working for me.

**Comment by beeblebrox3** [comment]
I found the problem. The script to prepare the package for publish apparently is not working. I update the version (twice), but the server code wasn't included :(

Now is all there:
![image](https://cloud.githubusercontent.com/assets/767624/25689285/154eed1a-305d-11e7-819d-a34c105aea7e.png)

Pleas, update to 1.0.6 version and see if is working for you now :)
Thanks for the help!
