### ISSUE TITLE
Incorrect report of undefined step for translated keywords that can have multiple values

### ISSUE THREAD

**Issue by bjinse** [beeblebrox3/vscode-behat-checker#15]
In the Dutch translation, the keyword "When" can be translated both with "Als" or "Wanneer"
Both are accepted by behat. See i18n.php line that contains (for Dutch translation):
'when' => 'Wanneer|Als|*',
behat -dl is only showing "Wanneer" in the sentences. Like:
default | Wanneer ik :seconds seconden wacht
(When I wait :seconds seconds)

In VS Code, if I use: 
Als ik 10 seconden wacht
The step is red underlined and reported as undefined in the "problems" tab.
If I use:
Wanneer ik 10 seconden wacht
Then nothing is underlined. Seems OK. But suddenly, no problem whatsoever are reported anymore
The same happens when I change the language in the first line.
When I change language to "fr" I expect all steps to be undefined, but no steps are undefined.

I looked into the source and see you use behat -di. If I use behat-di it shows:
default | [Wanneer|Als|*] ik :seconds seconden wacht
        | at `FeatureContext::ikSecondenWacht()`

I added caret and dollar sign to match other step definitions:
default | [When|*] /^ik :seconds seconden wacht$/
        | at `FeatureContext::ikSecondenWacht()`
But that makes no difference. 
I tried adding   "behatChecker.debug": true, to the user settings, but I do not see extra logging.

**Comment by beeblebrox3** [comment]
Thanks for the report, @bjinse 
I'll take a look

**Comment by bjinse** [comment]
If you need any help reproducing, please contact me.
I think a crucial part in reproducing is the first line of the feature file:

Example of my feature file:

# language: nl

Functionaliteit: Login vanaf de homepage
  Probeer in te loggen op de homepage van kleertjes

Achtergrond:
  # Gegeven dat ik op "/" ben
  # En ik het veld "temp_password" invul met "Kl33rtje5_2014"
  # En ik druk op "Send"
 
Scenario: Inloggen op de homepage
  Gegeven dat ik op "inloggen" ben
  Als ik inlog met gebruikersnaam "bjinse@xs4all.nl.test" en wachtwoord "JTw-Arz-DKu-Z6Z"
  Dan moet ik ingelogd zijn

Scenario: Inloggen op de homepage met fout wachtwoord werkt niet
  Gegeven dat ik op "inloggen" ben
  Als ik inlog met gebruikersnaam "bjinse@xs4all.nl.test" en wachtwoord "x-xxxxxx-xxx"
  Dan moet ik niet ingelogd zijn

Scenario: Direct inloggen vanaf de homepage 
  Gegeven dat ik ingelogd ben met gebruikersnaam "bjinse@xs4all.nl.test" en wachtwoord "JTw-Arz-DKu-Z6Z"
  Dan moet ik ingelogd zijn

Scenario: Uitloggen
  Gegeven dat ik ingelogd ben met gebruikersnaam "bjinse@xs4all.nl.test" en wachtwoord "JTw-Arz-DKu-Z6Z"
  Als ik uitlog
  Dan moet ik niet ingelogd zijn


If I change “Als” to “Wanneer” this should still be OK.


Met vriendelijke groet,

Bjinse Veenstra

**Comment by beeblebrox3** [comment]
@bjinse I'm sorry for the delay, I'm not using PHP and behat anymore.
This issue still is a problem for you?

Thanks.

**Comment by beeblebrox3** [comment]
I'm closing this, as I don't know if its still relevant.
