### ISSUE TITLE
Change behat path

### ISSUE THREAD

**Issue by jpenna** [beeblebrox3/vscode-behat-checker#16]
It would be nice to have a configurable behat's path.
It currently requires you to have it in `/vendor/bin/behat`, but mine is in `/app/vendor/bin/behat`.

**Comment by PHLAK** [comment]
I would also like the ability to customize the path to behat or, at the very least, have it check for a global install (i.e. available in the `$PATH`) of behat if `/vendor/bin/behat` doesn't exists.

**Comment by beeblebrox3** [comment]
I see. I'll try to address this next week. Thanks!

**Comment by beeblebrox3** [comment]
Next version will include this feature

**Comment by beeblebrox3** [comment]
Done. Version 1.1.0 is available at marketplace. A new config is available:

```
{
    "behatChecker.behatPath": "app/vendor/bin/behat"
}

```

The path can be absolute or relative;
